name: Scheduled Email Reset

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:         # Manual run

permissions:
  contents: write  # Required to push state updates

jobs:
  send_reset_emails:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests

    - name: Run email reset script
      run: python send_reset_emails.py
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}

    - name: Commit updated state
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .state/user_batch_state.json
        git commit -m "Update state [bot]" || echo "No changes to commit"
        git push
